print("Velocity Calculator")
distance = int(input("Please enter value of distance (km):"))
time = int(input("Please enter value of time (h):"))
velocity = int(distance/time)
print("Velocity =", velocity, "km/h")